### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by manancodes** [manancodes/screenbows#13]
I would love to see an updated Readme.md with the right project setup steps and a introduction to the project. Feel free to use ChatGPT or any other AI

**Comment by manancodes** [comment]
Re-opening this one because the features need another line. The hex code can be added manually as well. Please play around with the deployed site to make the readme better.

**Comment by manancodes** [comment]
You can also add some screenshots like this 
https://x.com/SadanaManan/status/1686665292334718976?s=20

**Comment by manancodes** [comment]
Also, a contributors section can be added.

**Comment by joanita-51** [comment]
@manancodes, is anyone currently working on the updates? If not, I'd be interested in taking on the task.

**Comment by manancodes** [comment]
Go Ahead. @joanita-51

**Comment by manancodes** [comment]
@joanita-51 , would be great if you can add screenshots as well.

**Comment by joanita-51** [comment]
> @joanita-51 , would be great if you can add screenshots as well.

Alright @manancodes, should I add a license to the project too? If yes, which kind of license
