### ISSUE TITLE
Add a feature to generate random patterns

### ISSUE THREAD

**Issue by manancodes** [manancodes/screenbows#15]
- There should be a toggle that the user can turn on and off.
- When this toggle is turned on, a random pattern (dots, grid, waves etc) will be generated and added, probably via CSS. 
- This pattern can be either black/white or a colour contrasting with the base colour. 
- There is already a logic that selects black or white according to the base colour for better contrast.

Feel free to use chatGPT or other AI.

**Comment by pbelokon** [comment]
@manancodes  I am interested in working on this, could you please assign me

**Comment by manancodes** [comment]
> @manancodes I am interested in working on this, could you please assign me

Done. Let me know if you need help.

**Comment by pbelokon** [comment]
Thanks

**Comment by pbelokon** [comment]
@manancodes  could you please add hacktoberfest completed label to this issue

**Comment by manancodes** [comment]
I will do that, but it won't make any difference. The repo has hacktoberfest label so you will see it should anyways be included.
