### ISSUE TITLE
Add a Color Picker in the Hex code input box.

### ISSUE THREAD

**Issue by manancodes** [manancodes/screenbows#21]
A color picker should pop-up when using the Hex input to use a random hex code or select the color.

<img width="319" alt="Screenshot 2023-10-20 at 4 23 12 AM" src="https://github.com/manancodes/Screenbows/assets/54790263/fc49aa56-efb6-4080-947e-4f5f1732ea8e">

**Comment by Shuva15** [comment]
hey @manancodes can I work on this. I can do it

**Comment by manancodes** [comment]
Go Ahead

**Comment by Shuva15** [comment]
hey @manancodes I have implemented the feature, I just need to make it responsive, I will make a PR once I finish it, I think I did good but if you think differently let me know, here is a demo

https://github.com/manancodes/Screenbows/assets/107918666/613c631a-3bd4-48c2-8941-9b88d3002991

**Comment by manancodes** [comment]
LGTM! Does the colour of the logo and the GitHub button change according to the base colour for better visibility?

**Comment by Shuva15** [comment]
good point, I'll do it

**Comment by Shuva15** [comment]
@manancodes I am having a problem, I am using 'onMouseEnter' on the hex-box to display the color picker but mouseEnter won't work on a mobile device
 And also the color picker won't fit properly in a smaller screen, it covers the other buttons
 I think, the color picker feature should work for desktop only, what do you think

**Comment by manancodes** [comment]
You can use the scale property to minimise it. Also, maybe you can add it on the mouse click so that it opens when the user selects the hex code input.

**Comment by Shuva15** [comment]
@manancodes created a pull request #40  , check it out and let me know is everything right
