### ISSUE TITLE
PR template

### ISSUE THREAD

**Issue by manancodes** [manancodes/screenbows#22]
Please create a PR template for this repository so that people can submit better PRs.

**Comment by Jonniie** [comment]
Can I work on this? Also what set of instructions will be included in the PR template

**Comment by manancodes** [comment]
I'm open to suggestions.

**Comment by Jonniie** [comment]
Probably something like

"My PR closes #no"

 - [👨‍💻 Changes proposed(What did you do ?)]
- [✔️ Check List (Check all the applicable boxes)]
 [] My code follows the code style of this project.
 [] This PR does not contain plagiarized content.
 [] The title and description of the PR is clear and explains the approach.

[📷 Screenshots]

any other additions you might want?

**Comment by manancodes** [comment]
Yes, something like would work as the first version.

you can add these though, rewrite it according to other points.

-  Have you performed a self-review of the code?
-  Have you added proper comments wherever needed?


Also, add helper texts (comment them out) in the template.

**Comment by Jonniie** [comment]
Alright, I'll work on that and submit a PR

**Comment by manancodes** [comment]
Can you add this as well?
Have you used prettier. (Better text obviously)

**Comment by Jonniie** [comment]
You mean like adding a prettier config?
Config is not really needed. Just asking the user to run prettier once on their code.

**Comment by Jonniie** [comment]
Oooh, will include that.
