### ISSUE TITLE
Remove legacy code

### ISSUE THREAD

**Issue by manancodes** [manancodes/screenbows#29]
Please go through the whole repo and try to find unused code or things which are not supposed to be there.

For example:
https://github.com/manancodes/Screenbows/blob/911857b58d44f06686e0dc670bd9afd815db6fa4/src/Components/Console/index.js#L31-L36

The `Shuffle` word is not being used but the icon, so It can be removed.

**Comment by joanita-51** [comment]
I can work on this, can I go ahead?

**Comment by manancodes** [comment]
> I can work on this, can I go ahead?

Go ahead. I have assigned this to you.

**Comment by manancodes** [comment]
Another one that I found was, the buttons inside the console have 2 css classes doing the same thing. One can be removed.

**Comment by joanita-51** [comment]
> Another one that I found was, the buttons inside the console have 2 css classes doing the same thing. One can be removed.

Yes, I noticed that as well. Thank you @manancodes. However, It appears the word 'shuffle' is related to the 'material-symbols-outlined' class, as removing it results in the icon not being displayed.

**Comment by joanita-51** [comment]
> Another one that I found was, the buttons inside the console have 2 css classes doing the same thing. One can be removed.

Yes, I saw that too. However the shuffle word seems to be associated with the class  "material-symbols-outlined" because once removed, the icon is not displayed

**Comment by manancodes** [comment]
> > Another one that I found was, the buttons inside the console have 2 css classes doing the same thing. One can be removed.
> 
> Yes, I noticed that as well. Thank you @manancodes. However, It appears the word 'shuffle' is related to the 'material-symbols-outlined' class, as removing it results in the icon not being displayed.

Oh yes. You're correct. Sometimes shuffle is seen on slow rendering but I think that's fine. You can work on the other issue though.
